# Configuración para que no muestre el error en el json, y asi mejorar la seguridad
server:
  error:
    include-message: never
    include-stacktrace: never

# Configuracion para que muestre los colores en la salida por consola spring
spring:
  output:
    ansi:
      enabled: always

# Configuración de la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/departamento
    username: ${userMySql}
    password: ${passMySql}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false